name: Lint Code

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 ruff
        pip install -e .

    - name: Run linting checks
      run: |
        echo "Running Pylint..."
        pylint $(git ls-files '*.py') || true

        echo "Running Flake8..."
        flake8 || true

        echo "Running Ruff..."
        ruff check . || true

